# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8.0-jessie

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/ff14-weather-forecast-rest-api/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # deploy
      - add_ssh_keys:
          fingerprints:
            - ${FINGERPRINTS}

      - run:
          name: ssh-keygen
          command: ssh-keyscan -p ${SSH_PORT} ${HOST_NAME} >> ~/.ssh/known_hosts

      - deploy:
          name: deploy master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt install rsync -y
              rsync -av --delete --rsh="ssh -p ${SSH_PORT}" --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:${DOCUMENT_ROOT}
            fi

      - deploy:
          name: reboot server
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -p ${SSH_PORT} "pm2 startOrRestart ${DOCUMENT_ROOT}/pm2.yml"
            fi
